# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
  AWS_ACCESS_KEY_ID: $(AWS.AccessKeyID) 
  AWS_SECRET_ACCESS_KEY: $(AWS.SecretAccessKey)
  AWS_SESSION_TOKEN: $(AWS.SessionToken) 




pool:
  vmImage: 'ubuntu-latest'


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

#init backend
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    backendAWSBucketName: 'dev-timesheet-backend-state-beltaief-marwan'
    backendAWSKey: '$(AWS.AccessKeyID)'
#terraform apply

